import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navbar from './components/navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head><script src="https://kit.fontawesome.com/41c8b474e2.js" crossOrigin="anonymous"></script></head>
      <body className={inter.className}>
        <Navbar/>
        {children}
        </body>
    </html>
  )
}
